# Generated by Django 3.2.9 on 2021-11-25 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('created', 'created'), ('wip', 'wip'), ('done', 'done'), ('error', 'error')], default='created', max_length=8)),
                ('page_count', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('work_started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('done_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png_file', models.FileField(upload_to='')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='endpoints.work')),
            ],
        ),
    ]
