# Generated by Django 3.2.9 on 2021-11-25 16:57

from django.db import migrations, models
import endpoints.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='orig_pdf_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='output',
            name='png_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
        migrations.AlterField(
            model_name='work',
            name='pdf_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
    ]
