# Generated by Django 3.2.9 on 2021-11-25 17:05

from django.db import migrations, models
import endpoints.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_auto_20211125_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='png_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
        migrations.AlterField(
            model_name='work',
            name='pdf_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
    ]
