# Generated by Django 3.2.9 on 2021-11-26 08:49

from django.db import migrations, models
import endpoints.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_auto_20211125_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='png_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
        migrations.AlterField(
            model_name='work',
            name='pdf_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
    ]
