# Generated by Django 3.2.9 on 2021-12-01 11:46

from django.db import migrations, models
import endpoints.models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_auto_20211126_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='output',
            name='png_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
        migrations.AlterField(
            model_name='work',
            name='pdf_file',
            field=models.FileField(upload_to=endpoints.models.WorkPath.upload_to),
        ),
    ]
